[project]
name = "nccl-device-initiated-ccl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "clang-format>=21.1.6",
    "clang-tidy>=21.1.1",
    "cmake>=4.1.3",
    "openmpi>=5.0.9",
    "pre-commit>=4.4.0",
]
